---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

#additional_build_steps:
#  append:
#    - RUN alternatives --set python /usr/bin/python3
#    - COPY --from=quay.io/project-receptor/receptor:latest /usr/bin/receptor /usr/bin/receptor
#    - RUN mkdir -p /var/run/receptor
#    - RUN mkdir -p /usr/local/mitogen
#    - COPY mitogen-0.3.2 /usr/local/mitogen/
#    - ENV ANSIBLE_STRATEGY_PLUGINS=/usr/local/mitogen/ansible_mitogen/plugins/strategy
#    - ENV ANSIBLE_STRATEGY=mitogen_linear
#    - ADD run.sh /run.sh
#    - CMD /run.sh
#    - USER 1000
#    - RUN git lfs install
