name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registries:
    name: Push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder
          ansible-builder build --container-runtime=docker --tag=ghcr.io/${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Images
        run: |
          docker push ghcr.io/${{ github.repository }}

